// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\domain\service\service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	models "gophkeep/internal/core/models"
	requests "gophkeep/internal/core/requests"
	jwtmanager "gophkeep/internal/domain/jwtmanager"
	params "gophkeep/internal/presentation/params"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// AddPassword mocks base method.
func (m *MockIService) AddPassword(ctx context.Context, object *requests.PasswordRequestObject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPassword", ctx, object)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPassword indicates an expected call of AddPassword.
func (mr *MockIServiceMockRecorder) AddPassword(ctx, object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPassword", reflect.TypeOf((*MockIService)(nil).AddPassword), ctx, object)
}

// AddSecret mocks base method.
func (m *MockIService) AddSecret(ctx context.Context, object *requests.SecretRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSecret", ctx, object)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSecret indicates an expected call of AddSecret.
func (mr *MockIServiceMockRecorder) AddSecret(ctx, object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSecret", reflect.TypeOf((*MockIService)(nil).AddSecret), ctx, object)
}

// DeleteSecret mocks base method.
func (m *MockIService) DeleteSecret(ctx context.Context, secretID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", ctx, secretID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockIServiceMockRecorder) DeleteSecret(ctx, secretID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockIService)(nil).DeleteSecret), ctx, secretID)
}

// GetAllSecrets mocks base method.
func (m *MockIService) GetAllSecrets(ctx context.Context) ([]models.SecretInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSecrets", ctx)
	ret0, _ := ret[0].([]models.SecretInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSecrets indicates an expected call of GetAllSecrets.
func (mr *MockIServiceMockRecorder) GetAllSecrets(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSecrets", reflect.TypeOf((*MockIService)(nil).GetAllSecrets), ctx)
}

// GetSecret mocks base method.
func (m *MockIService) GetSecret(ctx context.Context, secretID int) (*models.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret", ctx, secretID)
	ret0, _ := ret[0].(*models.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockIServiceMockRecorder) GetSecret(ctx, secretID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockIService)(nil).GetSecret), ctx, secretID)
}

// LoginUser mocks base method.
func (m *MockIService) LoginUser(ctx context.Context, object params.AuthRequestObject) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", ctx, object)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockIServiceMockRecorder) LoginUser(ctx, object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockIService)(nil).LoginUser), ctx, object)
}

// Ping mocks base method.
func (m *MockIService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockIServiceMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockIService)(nil).Ping), ctx)
}

// RegisterUser mocks base method.
func (m *MockIService) RegisterUser(ctx context.Context, object params.AuthRequestObject) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, object)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockIServiceMockRecorder) RegisterUser(ctx, object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockIService)(nil).RegisterUser), ctx, object)
}

// UpdateSecret mocks base method.
func (m *MockIService) UpdateSecret(ctx context.Context, object *requests.SecretRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, object)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockIServiceMockRecorder) UpdateSecret(ctx, object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockIService)(nil).UpdateSecret), ctx, object)
}

// VerifyJWT mocks base method.
func (m *MockIService) VerifyJWT(arg0 string) (*jwtmanager.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyJWT", arg0)
	ret0, _ := ret[0].(*jwtmanager.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyJWT indicates an expected call of VerifyJWT.
func (mr *MockIServiceMockRecorder) VerifyJWT(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyJWT", reflect.TypeOf((*MockIService)(nil).VerifyJWT), arg0)
}
