// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\domain\service\secrets\sercrets_service.go

// Package mock_secrets is a generated GoMock package.
package mock_secrets

import (
	context "context"
	models "gophkeep/internal/core/models"
	requests "gophkeep/internal/core/requests"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSecretsService is a mock of SecretsService interface.
type MockSecretsService struct {
	ctrl     *gomock.Controller
	recorder *MockSecretsServiceMockRecorder
}

// MockSecretsServiceMockRecorder is the mock recorder for MockSecretsService.
type MockSecretsServiceMockRecorder struct {
	mock *MockSecretsService
}

// NewMockSecretsService creates a new mock instance.
func NewMockSecretsService(ctrl *gomock.Controller) *MockSecretsService {
	mock := &MockSecretsService{ctrl: ctrl}
	mock.recorder = &MockSecretsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretsService) EXPECT() *MockSecretsServiceMockRecorder {
	return m.recorder
}

// AddPassword mocks base method.
func (m *MockSecretsService) AddPassword(ctx context.Context, object *requests.PasswordRequestObject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPassword", ctx, object)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPassword indicates an expected call of AddPassword.
func (mr *MockSecretsServiceMockRecorder) AddPassword(ctx, object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPassword", reflect.TypeOf((*MockSecretsService)(nil).AddPassword), ctx, object)
}

// AddSecret mocks base method.
func (m *MockSecretsService) AddSecret(ctx context.Context, object *requests.SecretRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSecret", ctx, object)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSecret indicates an expected call of AddSecret.
func (mr *MockSecretsServiceMockRecorder) AddSecret(ctx, object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSecret", reflect.TypeOf((*MockSecretsService)(nil).AddSecret), ctx, object)
}

// DeleteSecret mocks base method.
func (m *MockSecretsService) DeleteSecret(ctx context.Context, secretID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", ctx, secretID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockSecretsServiceMockRecorder) DeleteSecret(ctx, secretID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockSecretsService)(nil).DeleteSecret), ctx, secretID)
}

// GetAllSecrets mocks base method.
func (m *MockSecretsService) GetAllSecrets(ctx context.Context) ([]models.SecretInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSecrets", ctx)
	ret0, _ := ret[0].([]models.SecretInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSecrets indicates an expected call of GetAllSecrets.
func (mr *MockSecretsServiceMockRecorder) GetAllSecrets(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSecrets", reflect.TypeOf((*MockSecretsService)(nil).GetAllSecrets), ctx)
}

// GetSecret mocks base method.
func (m *MockSecretsService) GetSecret(ctx context.Context, secretID int) (*models.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret", ctx, secretID)
	ret0, _ := ret[0].(*models.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockSecretsServiceMockRecorder) GetSecret(ctx, secretID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockSecretsService)(nil).GetSecret), ctx, secretID)
}

// UpdateSecret mocks base method.
func (m *MockSecretsService) UpdateSecret(ctx context.Context, object *requests.SecretRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, object)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockSecretsServiceMockRecorder) UpdateSecret(ctx, object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockSecretsService)(nil).UpdateSecret), ctx, object)
}
